apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: random-giphy
  name: random-giphy
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: random-giphy
  template:
    metadata:
      labels:
        app: random-giphy
    spec:
      containers:
      - image: registry.gitlab.com/mrkwskiti/godal-container-registries/random-giphy
        imagePullPolicy: Always
        name: random-giphy
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      imagePullSecrets:
      - name: godal-gitlab-container-registries
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
