apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: registry.gitlab.com/mrkwskiti/godal-container-registries/random-giphy
  newTag: "0.0.1"
