apiVersion: v1
kind: Service
metadata:
  labels:
    run: random-giphy
  name: random-giphy
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: random-giphy
  sessionAffinity: None
  type: ClusterIP
